# This file was generated by GoReleaser. DO NOT EDIT.
cask "squirrel" do
  name "squirrel"
  desc "Find your forgotten Claude Code projects"
  homepage "https://github.com/dkd-dobberkau/squirrel"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squirrel"

  on_macos do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_amd64.tar.gz"
      sha256 "91eb91ebe35e9e2ad62305d5c9519dd2bfb3f81b3debb7f01ebaacc0ea3b4af1"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_arm64.tar.gz"
      sha256 "8e7d24ac9da12a8b565f2263e988333556ef976291ca1d4070a08493eecde8b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_amd64.tar.gz"
      sha256 "753e5c93322daf567a1f93aac97e3b8b04daaa31c87609116f0467bf467805d3"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_arm64.tar.gz"
      sha256 "e835dfe5fe542f6be9137bdd3200ff5f3c7ff56045536e0a987a40c6fa6caa6e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/squirrel"]
  end

  caveats do
    "If macOS blocks the binary, run: xattr -d com.apple.quarantine $(which squirrel)"
  end

  # No zap stanza required
end
