# This file was generated by GoReleaser. DO NOT EDIT.
cask "squirrel" do
  name "squirrel"
  desc "Find your forgotten Claude Code projects"
  homepage "https://github.com/dkd-dobberkau/squirrel"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squirrel"

  on_macos do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_amd64.tar.gz"
      sha256 "f782135d8aa25b3cb8ba2f038afb9c546933d6a2259fd4cd8b725f7f69bd5734"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_arm64.tar.gz"
      sha256 "9af8f524b4fe96fdccbdc1deb1d52b87e5613b790a33e9a90ae9e698ec8473a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_amd64.tar.gz"
      sha256 "c6309ae13a1424d9ee20e8ff0ba973c473a8d966caa928c089c34ba290761f64"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_arm64.tar.gz"
      sha256 "bb52fe5ca0dc6db8cb8799e6135b9772ad35a69cab0ae553387dd7056825b87f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/squirrel"]
  end

  caveats do
    "If macOS blocks the binary, run: xattr -d com.apple.quarantine $(which squirrel)"
  end

  # No zap stanza required
end
