# This file was generated by GoReleaser. DO NOT EDIT.
cask "squirrel" do
  name "squirrel"
  desc "Find your forgotten Claude Code projects"
  homepage "https://github.com/dkd-dobberkau/squirrel"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squirrel"

  on_macos do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_amd64.tar.gz"
      sha256 "d653cde0b75b8cc32ed150f4794a9c962b9f4ee8f21c206cba06deefe46c3a49"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_darwin_arm64.tar.gz"
      sha256 "b4c60a3c351469999cada37b8f0099e6901e913547d650f198f16517a1286056"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_amd64.tar.gz"
      sha256 "cdf2daeb6da30adff383e31710baf7050fa707c1f850f7dde72c6d8ceb37e910"
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/squirrel/releases/download/v#{version}/squirrel_#{version}_linux_arm64.tar.gz"
      sha256 "0853987d9cb9422bc9ea3c82581f040bcc4c95fdb3d92c044a91a8c1d61cde6a"
    end
  end

  # No zap stanza required
end
