# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccs < Formula
  desc "Claude Code Summary - local usage stats in your terminal"
  homepage "https://github.com/dkd-dobberkau/ccs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/ccs/releases/download/v0.1.0/ccs-darwin-amd64"
      sha256 "934c0a09913b9b7b28973548eec17d8a61beaf106e46128433ad64261707a1f3"

      def install
        bin.install "ccs-darwin-amd64" => "ccs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/ccs/releases/download/v0.1.0/ccs-darwin-arm64"
      sha256 "a0661685563ba7b8405161372851eeabffccfcfc9bbc74cad65dba14e34fcb21"

      def install
        bin.install "ccs-darwin-arm64" => "ccs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ccs/releases/download/v0.1.0/ccs-linux-amd64"
      sha256 "f9bc7d27fa8027e245b478efffb9d35618cdc7dc20615ded6bdc4b9f54193abf"
      def install
        bin.install "ccs-linux-amd64" => "ccs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ccs/releases/download/v0.1.0/ccs-linux-arm64"
      sha256 "e2da16251d7e704cc186dcb138cbada85964292a6998457bfe4ea80e12fb5a67"
      def install
        bin.install "ccs-linux-arm64" => "ccs"
      end
    end
  end

  test do
    system "#{bin}/ccs", "version"
  end
end
