# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeMeister < Formula
  desc "CLI/TUI tool to clean up forgotten Claude Code projects"
  homepage "https://github.com/dkd-dobberkau/claude-meister"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/claude-meister/releases/download/v0.1.0/claude-meister_0.1.0_darwin_amd64.tar.gz"
      sha256 "21ed00455898ba93080116eef0ad0f3830bfd8b8b643e8f336b599fb9cd3f5a1"

      define_method(:install) do
        bin.install "claude-meister"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/claude-meister/releases/download/v0.1.0/claude-meister_0.1.0_darwin_arm64.tar.gz"
      sha256 "6271b43a6387145edb85389cd1f0bf50731faec07972f8105ea8a9eb134f6858"

      define_method(:install) do
        bin.install "claude-meister"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/claude-meister/releases/download/v0.1.0/claude-meister_0.1.0_linux_amd64.tar.gz"
      sha256 "be87d742c4dc89a2ea7b03e5481b51fb04ed6f10794167c02132e31949d508f3"
      define_method(:install) do
        bin.install "claude-meister"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/claude-meister/releases/download/v0.1.0/claude-meister_0.1.0_linux_arm64.tar.gz"
      sha256 "32a64ccacf800fba746d7bd4e8d3ed3a3325422a5aac9d19736139629b78b0a1"
      define_method(:install) do
        bin.install "claude-meister"
      end
    end
  end
end
