# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeInsightsAgent < Formula
  desc "Sync Claude Code sessions to team server"
  homepage "https://github.com/dkd-dobberkau/claude-insights-agent"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.3/claude-insights-agent-darwin-amd64"
      sha256 "6b16ea9303b3a3fb4f045785fe415f18addc5b3269964cb2d6ee0e878d7f6746"

      def install
        bin.install "claude-insights-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.3/claude-insights-agent-darwin-arm64"
      sha256 "ca2e890d5ca77492dec56b9a3d4290017fe2a35fda202c3874f55ae13573b7ba"

      def install
        bin.install "claude-insights-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.3/claude-insights-agent-linux-amd64"
      sha256 "cae8e7e131990f124cab4b3fa144125608217e0e991be3b99a075a9273576bef"
      def install
        bin.install "claude-insights-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.3/claude-insights-agent-linux-arm64"
      sha256 "6ed0820a1bcda2842afee9ea4f199ef4c58028ccdf6026362001f9c1dcdb6512"
      def install
        bin.install "claude-insights-agent"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        claude-insights-agent init

      To run as a background service:
        brew services start claude-insights-agent
    EOS
  end

  service do
    run [opt_bin/"claude-insights-agent", "run"]
    keep_alive true
    log_path var/"log/claude-insights-agent.log"
    error_log_path var/"log/claude-insights-agent.log"
  end

  test do
    system "#{bin}/claude-insights-agent", "version"
  end
end
