# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeInsightsAgent < Formula
  desc "Sync Claude Code sessions to team server"
  homepage "https://github.com/dkd-dobberkau/claude-insights-agent"
  version "0.3.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.7/claude-insights-agent-darwin-amd64"
      sha256 "b05bcb62343dbd5acc58c0037d3b1dc90fb9ada074f2e0cbc172c6e11eadebd8"

      def install
        bin.install "claude-insights-agent-darwin-amd64" => "claude-insights-agent"
      end
    end
    on_arm do
      url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.7/claude-insights-agent-darwin-arm64"
      sha256 "4edd70873b147a0fc921f4efea35f968321269461cde9426a53732aa02262dde"

      def install
        bin.install "claude-insights-agent-darwin-arm64" => "claude-insights-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.7/claude-insights-agent-linux-amd64"
        sha256 "482830d3ef8594142ada21f1eb8aff016d6a1723730a803cf0077a798f0257d1"

        def install
          bin.install "claude-insights-agent-linux-amd64" => "claude-insights-agent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dkd-dobberkau/claude-insights-agent/releases/download/v0.3.7/claude-insights-agent-linux-arm64"
        sha256 "335b38537f4dbc9e73b72794a0508339f3424a2478f4aa9ddd5ded6264767fb4"

        def install
          bin.install "claude-insights-agent-linux-arm64" => "claude-insights-agent"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        claude-insights-agent init

      To run as a background service:
        brew services start claude-insights-agent
    EOS
  end

  service do
    run [opt_bin/"claude-insights-agent", "run"]
    keep_alive true
    log_path var/"log/claude-insights-agent.log"
    error_log_path var/"log/claude-insights-agent.log"
  end

  test do
    system bin/"claude-insights-agent", "version"
  end
end
