# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DdevMngr < Formula
  desc "CLI tool to manage DDEV projects with interactive TUI"
  homepage "https://github.com/dkd-dobberkau/ddev-mngr"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/ddev-mngr/releases/download/v0.3.0/ddev-mngr_0.3.0_darwin_amd64.tar.gz"
      sha256 "b62eca856837d53065282ab7015a5df9313ba879d1600fa39f875a9cfb36705b"

      def install
        bin.install "ddev-mngr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/ddev-mngr/releases/download/v0.3.0/ddev-mngr_0.3.0_darwin_arm64.tar.gz"
      sha256 "d7d0311fa37241b5d317f085630b8e2d147d0573cf2f3f28f96d323f92f243cb"

      def install
        bin.install "ddev-mngr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-mngr/releases/download/v0.3.0/ddev-mngr_0.3.0_linux_amd64.tar.gz"
      sha256 "31da78e18d36519792f61a37a3bf198b28ffb824e5bb19c5ac4436abfda1b679"
      def install
        bin.install "ddev-mngr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-mngr/releases/download/v0.3.0/ddev-mngr_0.3.0_linux_arm64.tar.gz"
      sha256 "f599c87bc5c631cdb3cb4922b563919bdeba45768701a2d6b815e00ed5853bea"
      def install
        bin.install "ddev-mngr"
      end
    end
  end

  test do
    system "#{bin}/ddev-mngr", "--help"
  end
end
