# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DdevExplain < Formula
  desc "CLI tool that summarizes DDEV project configurations"
  homepage "https://github.com/dkd-dobberkau/ddev-explain"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.3.0/ddev-explain_0.3.0_darwin_amd64.tar.gz"
      sha256 "4be4ea5f71543cfb9bb683819553220510dfa32df7b47d90cf34177e60bba6a7"

      def install
        bin.install "ddev-explain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.3.0/ddev-explain_0.3.0_darwin_arm64.tar.gz"
      sha256 "860c7d8df305957d780e6bf0cf8ec032905f73b4775728056e11f3f73dbe5a5a"

      def install
        bin.install "ddev-explain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.3.0/ddev-explain_0.3.0_linux_amd64.tar.gz"
      sha256 "16a254a39077c14153c435a2e562c96c2d440edcd4eec2733a789e3927b01954"
      def install
        bin.install "ddev-explain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.3.0/ddev-explain_0.3.0_linux_arm64.tar.gz"
      sha256 "e47f4326a541f977e446ba9acf43e4e2c254b890e9b94b9e09c5e5258628a2ac"
      def install
        bin.install "ddev-explain"
      end
    end
  end

  test do
    system "#{bin}/ddev-explain", "--help"
  end
end
