# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DdevExplain < Formula
  desc "CLI tool that summarizes DDEV project configurations"
  homepage "https://github.com/dkd-dobberkau/ddev-explain"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.2.0/ddev-explain_0.2.0_darwin_amd64.tar.gz"
      sha256 "0c9d044ee29cb69761c70bde27d6f8dac1f48866a76246782440c4298f64723a"

      def install
        bin.install "ddev-explain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.2.0/ddev-explain_0.2.0_darwin_arm64.tar.gz"
      sha256 "dd4552dbadb602d0dfaaad638b0c946f193dd246d0870336e45258c74363136e"

      def install
        bin.install "ddev-explain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.2.0/ddev-explain_0.2.0_linux_amd64.tar.gz"
      sha256 "7e3f16999d92bf884f9dcb33ba908898219b36ee735f763e63f50331f63f2ddb"
      def install
        bin.install "ddev-explain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkd-dobberkau/ddev-explain/releases/download/v0.2.0/ddev-explain_0.2.0_linux_arm64.tar.gz"
      sha256 "af8f2dfdf583e657f066a98778069d6c45a279e5e12004eebb2306cecc43ec83"
      def install
        bin.install "ddev-explain"
      end
    end
  end

  test do
    system "#{bin}/ddev-explain", "--help"
  end
end
